### ISSUE TITLE
直接导入RefreshControl使用出现编译错误

### ISSUE THREAD

**Issue by longminghong** [xhzengAIB/XHRefreshControl#19]
直接导入RefreshControl文件夹到项目之后，编译会在XHRefreshControl.h 等文件里面出现 "Expected a type" 这样的错误提示。

需要在XHRefreshControl.h里面#import <UIKit/UIKit.h>才能让编译通过。

**Comment by xhzengAIB** [comment]
是的，你还可以通过pod来安装
