### ISSUE TITLE
当UITableView中的cell个数比较少没有充满整个屏幕时，上拉会弹出“上拉加载更多”

### ISSUE THREAD

**Issue by shuijinliuxi** [xhzengAIB/XHRefreshControl#20]
我工程是继承XHSysatemRefreshTableViewController，最开始显示的cell数量很少，这时我想让XHSysatemRefreshTableViewController无法上拉，当cell数量能够充满整个屏幕或更多时，才能够上拉加载，应该怎么实现呢

**Comment by xhzengAIB** [comment]
你好！  这个时候你应该调用另外一个方法，让TableView无法支持上拉就ok了，https://github.com/xhzengAIB/XHRefreshControl/blob/master/RefreshControl/Controllers/SystemTableViewController/XHSysatemRefreshTableViewController.h#L75
或者https://github.com/xhzengAIB/XHRefreshControl/blob/master/RefreshControl/Controllers/SystemTableViewController/XHSysatemRefreshTableViewController.h#L82

**Comment by shuijinliuxi** [comment]
我试了，但是这样会有信息一直显示在最后一个cell下面，我想要的是不显示任何信息，直接无法上拉加载

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/XHRefreshControl/blob/master/RefreshControl/Controllers/SystemTableViewController/XHSysatemRefreshTableViewController.h#L75

这个方法，传入@""

**Comment by shuijinliuxi** [comment]
这个我试过了，没有显示任何信息，但是一个灰色的框在最下边，怎么去除呢

**Comment by xhzengAIB** [comment]
https://github.com/xhzengAIB/XHRefreshControl/blob/master/XHRefreshControlExample/XHRefreshControlExample/Controllers/CustomLoadMoreButtonDemoTableViewController/XHCustomLoadMoreButtonDemoTableViewController.m#L15
直接定制这个按钮的背景颜色

**Comment by shuijinliuxi** [comment]
嗯，可以了，tks

**Comment by xhzengAIB** [comment]
行了吧？
